### ISSUE TITLE
Open project member page occured 404

### ISSUE THREAD

**Issue by archonwang** [Eivy/redmine_project_member#1]
the error log as follow.I used redmine 3.2.x with ruby 2.2 and rails 4.2.5. 
I think you should filter the users without users.type is not Group.
Thanks.

> I, [2016-05-15T18:27:30.182813 #23077]  INFO -- : Completed 200 OK in 420ms (Views: 275.2ms | ActiveRecord: 54.3ms)
> I, [2016-05-15T18:27:35.039303 #23077]  INFO -- : Started GET "/web/project_member" for 192.168.60.239 at 2016-05-15 18:27:35 +0800
> I, [2016-05-15T18:27:35.041065 #23077]  INFO -- : Processing by ProjectMemberController#index as HTML
> I, [2016-05-15T18:27:35.041176 #23077]  INFO -- :   Parameters: {"id"=>"web"}
> I, [2016-05-15T18:27:35.047490 #23077]  INFO -- :   Current user: admin (id=1)
> I, [2016-05-15T18:27:35.304712 #23077]  INFO -- :   Rendered plugins/redmine_project_member/app/views/project_member/index.html.erb within layouts/base (17.6ms)
> I, [2016-05-15T18:27:35.305086 #23077]  INFO -- : Completed 500 Internal Server Error in 264ms (ActiveRecord: 6.8ms)
> I, [2016-05-15T18:27:35.314078 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.5ms)
> I, [2016-05-15T18:27:35.315484 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.3ms)
> I, [2016-05-15T18:27:35.318058 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.5ms)
> I, [2016-05-15T18:27:35.318859 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
> I, [2016-05-15T18:27:35.322002 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.1ms)
> I, [2016-05-15T18:27:35.322805 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
> I, [2016-05-15T18:27:35.324278 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
> I, [2016-05-15T18:27:35.324942 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
> I, [2016-05-15T18:27:35.325138 #23077]  INFO -- :   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.1.4/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (12.5ms)
> F, [2016-05-15T18:27:36.647003 #23077] FATAL -- : 
> ActiveRecord::RecordNotFound (Couldn't find User with 'id'=46 [WHERE `users`.`type` IN ('User', 'AnonymousUser')]):
>   plugins/wiking/lib/wiking_user_patch.rb:23:in `find'
>   plugins/redmine_project_member/app/views/project_member/index.html.erb:21:in`block in _plugins_redmine_project_member_app_views_project_member_index_html_erb__1960716888632943892_47751740'
>   plugins/redmine_project_member/app/views/project_member/index.html.erb:15:in `each'
>   plugins/redmine_project_member/app/views/project_member/index.html.erb:15:in`_plugins_redmine_project_member_app_views_project_member_index_html_erb__1960716888632943892_47751740'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by Eivy** [comment]
I fixed 404 error on project member page.

From Redmin 1.3, you can assign a group to issues.
So, project member page includes groups.

**Comment by archonwang** [comment]
@Eivy ,
I  will test it later , Thanks.
